(function(g){'use strict';
var U=g.RootworkUI,R=U.R,RD=g.ReactDOM,D=U.D,S=U.S,h=U.h,F=R.Fragment,I=U.I,Logo=U.Logo,Frame=U.Frame,Field=U.Field;
function Splash(){return h('div',{className:'splash',role:'status','aria-label':'Rootwork đang khởi động'},h('div',{className:'splash-rings','aria-hidden':'true'},h('i'),h('i'),h('i')),h('div',{className:'splash-lock'},Logo('splash-logo'),h('strong',null,'Rootwork'),h('p',null,'Nhỏ hôm nay, lớn ngày mai'),h('div',{className:'splash-loader','aria-hidden':'true'},h('span',null,h('i')),h('small',null,'Đang khởi động...'))),h('small',{className:'splash-copyright'},'© 2026 Rootwork · @derekdaydoi'))}
function Top(q){return h('header',{className:'top'},h('div',{className:'brand'},Logo('brand-logo'),h('strong',null,'Rootwork')),h('button',{className:'icon-btn',onClick:q.settings,'aria-label':'Cài đặt'},I('settings',21)))}
function GoalModal(q){var a=R.useState(''),title=a[0],setTitle=a[1],b=R.useState(''),desc=b[0],setDesc=b[1];return h(Frame,{title:'Tạo mục tiêu mới',close:q.close},h('form',{className:'form',onSubmit:function(e){e.preventDefault();if(title.trim()){q.addGoal(title.trim(),desc.trim());q.close()}}},Field('Tiêu đề mục tiêu',h('input',{autoFocus:true,value:title,onChange:function(e){setTitle(e.target.value)}})),Field('Mô tả',h('textarea',{rows:3,value:desc,onChange:function(e){setDesc(e.target.value)}})),h('button',{className:'primary'},'Tạo mục tiêu')))}
function TaskModal(q){var a=R.useState(''),title=a[0],setTitle=a[1],b=R.useState(q.m.targetId||''),target=b[0],setTarget=b[1],c=R.useState(q.m.date||''),date=c[0],setDate=c[1],d=R.useState('normal'),priority=d[0],setPriority=d[1];return h(Frame,{title:'Tác vụ tuần',close:q.close},h('form',{className:'form',onSubmit:function(e){e.preventDefault();if(title.trim()){q.addTask({title:title.trim(),targetId:target,date:date,priority:priority});q.close()}}},Field('Tác vụ',h('input',{autoFocus:true,value:title,onChange:function(e){setTitle(e.target.value)}})),Field('Mục tiêu',h('select',{value:target,onChange:function(e){setTarget(e.target.value)}},h('option',{value:''},'Tác vụ tuần độc lập'),(q.w.targets||[]).map(function(x){return h('option',{key:x.id,value:x.id},x.title)}))),Field('Ngày · không bắt buộc',h('input',{type:'date',min:q.w.startDate,max:q.w.endDate,value:date,onChange:function(e){setDate(e.target.value)}})),h('div',{className:'choice'},h('button',{type:'button',className:priority==='normal'?'active':'',onClick:function(){setPriority('normal')}},'Bình thường'),h('button',{type:'button',className:priority==='high'?'active':'',onClick:function(){setPriority('high')}},'Ưu tiên cao')),h('button',{className:'primary'},'Thêm tác vụ tuần')))}
function RoutineModal(q){var a=R.useState(''),name=a[0],setName=a[1],b=R.useState(3),target=b[0],setTarget=b[1];return h(Frame,{title:'Tạo routine',close:q.close},h('form',{className:'form',onSubmit:function(e){e.preventDefault();if(name.trim()){q.addRoutine(name.trim(),target);q.close()}}},Field('Tên routine',h('input',{autoFocus:true,value:name,onChange:function(e){setName(e.target.value)},placeholder:'Ví dụ: Tập thể dục 30 phút'})),Field('Mục tiêu mỗi tuần',h('select',{value:target,onChange:function(e){setTarget(Number(e.target.value))}},[1,2,3,4,5,6,7].map(function(n){return h('option',{value:n,key:n},n+' lần')}))),h('button',{className:'primary'},'Thêm routine')))}
function Settings(q){var f=R.useRef(null);return h(Frame,{title:'Cài đặt & dữ liệu',close:q.close},h('div',{className:'settings'},h('button',{className:'secondary',onClick:function(){S.exportBackup(q.data)}},'Xuất bản sao lưu'),h('input',{ref:f,type:'file',accept:'.json,application/json',className:'hidden',onChange:function(e){var file=e.target.files&&e.target.files[0];if(!file)return;S.importBackup(file,function(err,x){if(err)return g.alert(err);try{S.save(D.ensureCurrentWeek(x));g.location.reload()}catch(ex){g.alert(ex.message)}})}}),h('button',{className:'secondary',onClick:function(){if(f.current)f.current.click()}},'Khôi phục bản sao lưu'),h('p',null,'Rootwork là local-first. Hãy xuất backup trước khi xoá dữ liệu trình duyệt hoặc đổi domain.')))}
function Modals(q){if(q.m.type==='goal')return h(GoalModal,q);if(q.m.type==='task')return h(TaskModal,q);if(q.m.type==='routine')return h(RoutineModal,q);if(q.m.type==='settings')return h(Settings,q);return null}
function App(){var ds=R.useState(null),data=ds[0],setData=ds[1],vs=R.useState('dashboard'),view=vs[0],setView=vs[1],ms=R.useState(null),modal=ms[0],setModal=ms[1],ls=R.useState(true),launch=ls[0],setLaunch=ls[1],ref=R.useRef(null);
R.useEffect(function(){var n;try{n=D.ensureCurrentWeek(S.load()||S.empty())}catch(e){n=D.ensureCurrentWeek(S.empty())}var w=D.currentWeek(n);if(w&&w.phase!=='active'){w.phase='active';w.status='active';w.startedAt=w.startedAt||S.now();w.targets=(w.targets||[]).filter(function(x){return x.status!=='removed'})}ref.current=n;setData(n);try{S.save(n)}catch(e){}var tm=setTimeout(function(){setLaunch(false)},1900);return function(){clearTimeout(tm)}},[]);
function mut(fn){if(!ref.current)return;var n=D.clone(ref.current);fn(n);n.schemaVersion=S.SCHEMA;n.meta=Object.assign({},n.meta||{},{updatedAt:S.now()});ref.current=n;setData(n);try{S.save(n)}catch(e){}}
function toggleTask(x){mut(function(n){var t=D.findTask(n,x);if(t){t.done=!t.done;t.completedAt=t.done?S.now():null}})}
function addGoal(a,b){mut(function(n){D.currentWeek(n).targets.push({id:S.uid(),title:a,description:b||'',status:'active',tasks:[]})})}
function addTask(x){mut(function(n){D.attachTask(D.currentWeek(n),x.targetId||null,{id:S.uid(),title:x.title,note:'',priority:x.priority==='high'?'high':'normal',done:false,date:x.date||null,time:null,completedAt:null})})}
function addRoutine(name,target){mut(function(n){n.routines=n.routines||[];n.routines.push({id:S.uid(),name:name,recurrence:{type:'weekly',target:Math.max(1,Math.min(7,Number(target)||3))},log:{}})})}
function toggleRoutine(id,date){mut(function(n){var r=(n.routines||[]).find(function(x){return x.id===id});if(!r)return;r.log=r.log||{};if(r.log[date])delete r.log[date];else r.log[date]=true})}
if(!data)return h(Splash);
var w=D.currentWeek(data),p={data:data,w:w,go:function(v){setView(v);g.scrollTo(0,0)},toggleTask:toggleTask,toggleRoutine:toggleRoutine,addGoal:function(){setModal({type:'goal'})},addTask:function(id,date){setModal({type:'task',targetId:id||'',date:date||''})},addRoutine:function(){setModal({type:'routine'})}};
var V={dashboard:U.Dashboard,goals:U.Goals,calendar:U.Calendar,routines:U.Routines,progress:U.Progress};
return h(F,null,launch&&h(Splash),h('main',{className:'shell'},view==='dashboard'&&h(Top,{settings:function(){setModal({type:'settings'})}}),h(V[view],p)),h(U.Nav,{v:view,go:p.go}),modal&&h(Modals,{m:modal,data:data,w:w,close:function(){setModal(null)},addGoal:addGoal,addTask:addTask,addRoutine:addRoutine}))}
var mount=document.getElementById('root');if(RD.createRoot)RD.createRoot(mount).render(h(App));else RD.render(h(App),mount);if('serviceWorker'in navigator)g.addEventListener('load',function(){navigator.serviceWorker.register('./sw.js').catch(function(){})});
})(window);
